sudo: false
dist: bionic
language: python
python:
- '3.6'
notifications:
  email: false
install:
- pip install pipenv
- pipenv install --ignore-pipfile --dev
script:
- pipenv run pytest
deploy:
  provider: pypi
  user: snyk
  password:
    secure: iVYTa42kB2yfA/nbGdYzkSLt9mANSTA5cHLuQyaeXpIKv4H189kr+VBKIAYk6Q/pjg9z2q7INGBfrUetO5hfpFAgp92n8oCvW6v6NeMZxs+G6JsUQ9rdCNJfPfO/7TvD/X3w+6o3Ob1Y9lmYK/3v8Q2vkc+S9+4AIW9wMgC1WqWom+X7gJFMLQaFZqaZzNkZbQXzALHJPdvmO9zaY5W+0yXw8rXG1CKqzxpKPPTELav0ndcrmbhr8vUUaKZl1EseJYhDGiqyL0duOrZU0bJbF4N4tyHV9PicvQBAMDiHUB6HK5Qx4P1gqtE6OgmMTimQ/iXlKzH3yZbPgYfzXFvm6CN6+qFf57P9n/XzAwo0fCORsNc8DnyD+RbwSCqZUSaJsl8tUf2WCd23f2YtZi52xe3cZMc0RLvUUZmkklO7z3ZyerZGtAeMJ4eFYG1N7qhwqUeuk9TWH3zKPJMBdlkSQdbwQ5eVU1c1GdA1eKs+AF+4WGfpEVUpTuL1sYD/9N61stOa6bCFIejhynaPJQedt0/d9/loyzqdkHDyranQt1eN0laMMnUX0v2wQLtAu0beO+yZegvcQHR39DlllMGtEeZN4z63o4PwI3GGlhTU+UzafCBgSaoE2lrPq5VCINCgiSgh5dVbbu3IIRiOYn+R7nWcg4doK/dlYkSPdl5MckI=
  on:
    branch: master
branches:
  only:
  - master
