sudo: false
dist: trusty
language: python
python:
  - "3.6"
notifications:
  email: false
install:
  - "pip install pipenv"
  - "pipenv install --ignore-pipfile --dev"
script:
  - "pipenv run pytest"
deploy:
  provider: pypi
  user: "snyk"
  password:
    secure: "c7Dgu4DDBYU5EUWhjqQcE3EnjI0/bANQF/7YQsUoRQBU1hBLE0PruHUVJKFcP/KU4QxRTA9MjogesvEeFLdk6JQtiMDHDKcysQOhMJgBijt+y2lDzAEy+pXIuYsCdRLnfkriuxM75GDwTEDQuRF+0iK1HjanPKgmu+PYSx04sTReW6qC3KAM0V0g98aAafjcAHn8yjm34f+4/R32XSl8VkH4CcPXTvScEqTdgtiGfO35yhXknCXVFrqMbQ+gxIlkXG09tx7sfMRMHrE+E8H76YRllhPfsvR0fSUI/8xw/uK4+ORtJituw1t/MWQXHiA+HlC1c0OwRX4MJN24BbjRdF9xNPddz4yAB17q50286CboWvEjzy34fUH+4h3N8peACvKoOC/yQpyFRTfqe1VZEgGGo9DLXMPZ4nWZibLprMyHOawsPV+fOW2RoRvoWkzKqr6PaUJ209L2wA03ZFSbyTyImNRue56EZkxOlvreuCh4LzfDLlFsGKeXgo18znR8Ev9bAsP+llAFqacVzDU09wAoepRfTglarwoIu5QinUnX1d7Zs8aymqUkuOfxVID6uTlWK4EUNusuQRJx+pP1L3ujtEEXKHBWns/afjiq50H0PNQXmX5FFopXP9t6rDLwET6FiHdRz2SkwBUnvrYvzcETuVH68z/FAxXFmdw6d90="
  on:
    branch: master
branches:
  only:
   - master
